
/* 1. vaicajums */
/* firstly compare by STRADA_NO then by STRADA_LIDZ */
/* only apsargs */
select LDGS.VARDS as vards,
       LDGS.UZVARDS as uzvards, LDGS.DARBA_POZICIJA as darbs,
       TO_CHAR (LDGS.STRADA_NO, 'YYYY-MM-DD HH24:MI:SS') strada_no,
       TO_CHAR (LDGS.STRADA_LIDZ, 'YYYY-MM-DD HH24:MI:SS') strada_lidz,
       MIN(LDGS.STRADA_NO) OVER (ORDER BY LDGS.STRADA_NO ROWS 1 PRECEDING) as SN2,
       MIN(LDGS.STRADA_LIDZ) OVER (ORDER BY LDGS.STRADA_LIDZ ROWS 1 PRECEDING) as SL2
from LIDOSTA_DARBINIEKS_GRAFIKS_SKATS LDGS
         inner join LIDOSTA_GRAFIKS_SKATS LGS on LDGS.LIDOSTA_ID = LGS.LIDOSTA_ID and LDGS.NEDELAS_DIENA = LGS.NEDELAS_DIENA
where ((VALUE (LDGS).SAKTS_AR(LGS.DATUMS_NO, LGS.DATUMS_LIDZ)) = 1 or (VALUE (LDGS).BEIDZAS_AR(LGS.DATUMS_NO, LGS.DATUMS_LIDZ)) = 1)
  and LDGS.DARBA_POZICIJA like '%apsargs%'
;

/* 2. vaicajums */
select LDGS.VARDS, LDGS.UZVARDS,
       LDGS.DARBA_POZICIJA,
       TO_CHAR (LDGS.STRADA_NO, 'YYYY-MM-DD HH24:MI:SS') "strada_no",
       TO_CHAR (LDGS.STRADA_LIDZ, 'YYYY-MM-DD HH24:MI:SS') "strada_lidz",
       LS.NOSAUKUMS,
       MIN(TO_CHAR (LS.DATUMS_NO, 'YYYY-MM-DD HH24:MI:SS')) OVER ( ORDER BY LS.DATUMS_NO ROWS 1 PRECEDING) as DN2,
       MIN(TO_CHAR (LS.DATUMS_LIDZ, 'YYYY-MM-DD HH24:MI:SS')) OVER ( ORDER BY LS.DATUMS_LIDZ ROWS 1 PRECEDING) as DL2
from LIDOSTA_DARBINIEKS_GRAFIKS_SKATS LDGS
         inner join LIDOJUMS_SKATS LS on (DEREF(LS.LIDOSTA_NO).LIDOSTA_ID = LDGS.LIDOSTA_ID or
                                          DEREF(LS.LIDOSTA_UZ).LIDOSTA_ID = LDGS.LIDOSTA_ID)
where ((VALUE(LS).SAKTS_AR(LDGS.STRADA_NO, LDGS.STRADA_LIDZ) = 1 and DEREF(LS.LIDOSTA_NO).LIDOSTA_ID = LDGS.LIDOSTA_ID) or
       (VALUE(LS).BEIDZAS_AR(LDGS.STRADA_NO, LDGS.STRADA_LIDZ) = 1 and DEREF(LS.LIDOSTA_UZ).LIDOSTA_ID = LDGS.LIDOSTA_ID)) and
        LDGS.DARBA_POZICIJA like '%despetceris%';
;